### ISSUE TITLE
Unfiltered replies

### ISSUE THREAD

**Issue by clamiax** [mar77i/local_scan#1]
Hello,

thank you for this helpful tool. I've just noticed that listener() prints out all incoming ICMP packets instead of the ones generated by local_scan. I think that this refinement is not worth the added complexity so you deliberately decided not to implementing it. Though it is somewhat unexpected to see non-related ICMP packets, that's why I opened an issue. What are your thoughts about?

Regards,
Claudio

**Comment by mar77i** [comment]
I totally haven't thought about anything remotely resembling what you describe. I appear to be the sole user of ICMP around here, and I guess you could add a length check and a `strcmp()` on the received message. Thinking about it, we might also use a constant string instead of digits.

Cheers!

**Comment by mar77i** [comment]
If you need uniqueness, you can always `|sort|uniq`, and my intention in the implementation is a sort of "are-hosts-alive" test. It really wouldn't occur to me to produce other traffic on the protocol in question.

**Comment by mar77i** [comment]
Thinking about it, would uniquely reporting on responding IPs be a viable solution? That way already existing traffic would not interfer with the author's intention. @clamiax would that be a viable solution, that plus the comparison of the packet body?

**Comment by clamiax** [comment]
Well, it's not 100% correct but I think it should do the job 100% of the time (in real use cases). Though I wonder how complex is to match the identifier and the sequence number on the packets.

**Comment by mar77i** [comment]
If you come with the facts, I'll get coding 👍

**Comment by clamiax** [comment]
I think this may solve most of the problem: http://sprunge.us/jcHF
